//@version=5
indicator(shorttitle="FBB HTF", title="Fibonacci Bollinger Bands (High Time Frame)", overlay=true)

// Inputs
length = input.int(200, minval=1, title="Length")
src = input(hlc3, title="Source")
mult = input.float(3.0, minval=0.001, maxval=50, title="Multiplier")
htf = input.timeframe("", title="Higher Time Frame (Opcional)")

// Função para obter dados do timeframe superior
htf_src = request.security(syminfo.tickerid, htf, src)
htf_basis = request.security(syminfo.tickerid, htf, ta.vwma(src, length))
htf_dev = request.security(syminfo.tickerid, htf, ta.stdev(src, length))

// Cálculos
basis = htf == "" ? ta.vwma(src, length) : htf_basis
dev = htf == "" ? ta.stdev(src, length) : htf_dev

upper_1 = basis + (0.236 * mult * dev)
upper_2 = basis + (0.382 * mult * dev)
upper_3 = basis + (0.5 * mult * dev)
upper_4 = basis + (0.618 * mult * dev)
upper_5 = basis + (0.764 * mult * dev)
upper_6 = basis + (1 * mult * dev)
lower_1 = basis - (0.236 * mult * dev)
lower_2 = basis - (0.382 * mult * dev)
lower_3 = basis - (0.5 * mult * dev)
lower_4 = basis - (0.618 * mult * dev)
lower_5 = basis - (0.764 * mult * dev)
lower_6 = basis - (1 * mult * dev)

// Plotagem
plot(basis, color=color.fuchsia, linewidth=2)
p1 = plot(upper_1, color=color.white, linewidth=1, title="0.236")
p2 = plot(upper_2, color=color.white, linewidth=1, title="0.382")
p3 = plot(upper_3, color=color.white, linewidth=1, title="0.5")
p4 = plot(upper_4, color=color.white, linewidth=1, title="0.618")
p5 = plot(upper_5, color=color.white, linewidth=1, title="0.764")
p6 = plot(upper_6, color=color.red, linewidth=2, title="1")
p13 = plot(lower_1, color=color.white, linewidth=1, title="0.236")
p14 = plot(lower_2, color=color.white, linewidth=1, title="0.382")
p15 = plot(lower_3, color=color.white, linewidth=1, title="0.5")
p16 = plot(lower_4, color=color.white, linewidth=1, title="0.618")
p17 = plot(lower_5, color=color.white, linewidth=1, title="0.764")
p18 = plot(lower_6, color=color.green, linewidth=2, title="1")
